import Header from "@/components/Header";
import "./globals.css";
import Providers from "./Providers";
import Tabs from "@/components/Tabs";

export const metadata = {
  title: "MovieApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Tabs />
          {children}
        </Providers>
      </body>
    </html>
  );
}
